"""
Vittantra - Exposure-Aware Portfolio Rebalancer

Purpose
-------
Build a portfolio rebalancing layer on top of the Day 64 exposure engine.

This module deliberately separates:

1. Capital allocation
2. Gross notional exposure
3. Signed notional exposure
4. Risk exposure

This is especially important for derivatives, where notional exposure should
not automatically be interpreted as fully funded capital.

Inputs
------
day64_instrument_exposures.csv

Outputs
-------
day65_exposure_aware_orders.csv
day65_target_exposures.csv
day65_portfolio_summary.csv
day65_constraint_checks.csv
day65_validation_summary.csv

Important
---------
This is a research and portfolio-risk framework. Proposed rebalances are
analytical outputs, not automatic trade instructions.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Iterable

import numpy as np
import pandas as pd

from vittantra_risk_model import (
    load_enriched_instruments,
    load_risk_history,
    portfolio_risk_shares,
)


# ======================================================================
# CONFIGURATION
# ======================================================================

INPUT_FILE = Path("day64_instrument_exposures.csv")

OUTPUT_ORDERS = Path("day65_exposure_aware_orders.csv")
OUTPUT_TARGETS = Path("day65_target_exposures.csv")
OUTPUT_SUMMARY = Path("day65_portfolio_summary.csv")
OUTPUT_CHECKS = Path("day65_constraint_checks.csv")
OUTPUT_VALIDATION = Path("day65_validation_summary.csv")


@dataclass(frozen=True)
class Policy:
    # Fully funded capital concentration.
    max_capital_weight: float = 0.25

    # Gross economic exposure relative to total capital.
    max_single_instrument_gross_exposure: float = 1.00

    # Risk concentration.
    max_single_instrument_risk_weight: float = 0.35

    # Portfolio-level gross exposure.
    max_portfolio_gross_exposure: float = 2.00

    # Portfolio-level absolute signed notional.
    max_portfolio_absolute_notional: float = 2.00

    # Maximum one-way turnover generated by this layer.
    max_one_way_turnover: float = 0.35

    # Ignore economically tiny trades.
    trade_tolerance: float = 0.001

    # Numerical tolerance.
    epsilon: float = 1e-10


POLICY = Policy()


# ======================================================================
# UTILITIES
# ======================================================================

def normalize_name(value: str) -> str:
    return (
        str(value)
        .strip()
        .lower()
        .replace(" ", "_")
        .replace("-", "_")
        .replace("/", "_")
    )


def find_column(
    df: pd.DataFrame,
    candidates: Iterable[str],
    required: bool = True,
) -> str | None:
    lookup = {normalize_name(c): c for c in df.columns}

    for candidate in candidates:
        key = normalize_name(candidate)
        if key in lookup:
            return lookup[key]

    if required:
        raise KeyError(
            "Could not locate required column.\n"
            f"Tried: {list(candidates)}\n"
            f"Available columns: {df.columns.tolist()}"
        )

    return None


def numeric(series: pd.Series, fill_value: float = 0.0) -> pd.Series:
    return pd.to_numeric(series, errors="coerce").fillna(fill_value)


def safe_divide(
    numerator: pd.Series | np.ndarray | float,
    denominator: float,
) -> pd.Series | np.ndarray | float:
    if abs(denominator) <= POLICY.epsilon:
        if isinstance(numerator, pd.Series):
            return pd.Series(0.0, index=numerator.index)
        if isinstance(numerator, np.ndarray):
            return np.zeros_like(numerator, dtype=float)
        return 0.0

    return numerator / denominator


def finite(value: float) -> bool:
    return bool(np.isfinite(value))


def choose_identifier_column(df: pd.DataFrame) -> str:
    return find_column(
        df,
        [
            "symbol",
            "ticker",
            "instrument",
            "security",
            "asset",
            "identifier",
            "name",
        ],
    )


# ======================================================================
# LOAD + STANDARDIZE DAY 64
# ======================================================================

def load_day64() -> pd.DataFrame:
    if not INPUT_FILE.exists():
        raise FileNotFoundError(
            f"Required input not found: {INPUT_FILE}"
        )

    raw = pd.read_csv(INPUT_FILE)

    if raw.empty:
        raise ValueError("Day 64 instrument exposure file is empty.")

    symbol_col = choose_identifier_column(raw)

    asset_class_col = find_column(raw, ["asset_class"])
    instrument_type_col = find_column(raw, ["instrument_type"])

    quantity_col = find_column(raw, ["quantity"])
    price_col = find_column(raw, ["price"])
    multiplier_col = find_column(raw, ["contract_multiplier"])

    market_value_col = find_column(raw, ["market_value"])
    current_weight_col = find_column(raw, ["current_weight"])

    capital_factor_col = find_column(raw, ["capital_factor"])
    notional_factor_col = find_column(raw, ["notional_factor"])
    risk_multiplier_col = find_column(raw, ["risk_multiplier"])

    capital_exposure_col = find_column(raw, ["capital_exposure"])
    signed_notional_col = find_column(raw, ["signed_notional_exposure"])
    gross_notional_col = find_column(raw, ["gross_notional_exposure"])
    risk_exposure_col = find_column(raw, ["risk_exposure"])

    capital_weight_col = find_column(raw, ["capital_weight"])
    gross_weight_col = find_column(raw, ["gross_exposure_weight"])
    signed_notional_weight_col = find_column(
        raw,
        ["signed_notional_weight"],
    )
    risk_weight_col = find_column(raw, ["risk_weight"])
    notional_weight_col = find_column(raw, ["notional_weight"])

    df = pd.DataFrame(
        {
            "symbol": raw[symbol_col].astype(str),
            "asset_class": raw[asset_class_col].astype(str),
            "instrument_type": raw[instrument_type_col].astype(str),
            "quantity": numeric(raw[quantity_col]),
            "price": numeric(raw[price_col]),
            "contract_multiplier": numeric(raw[multiplier_col]),
            "market_value": numeric(raw[market_value_col]),
            "day64_current_weight": numeric(raw[current_weight_col]),
            "capital_factor": numeric(raw[capital_factor_col]),
            "notional_factor": numeric(raw[notional_factor_col]),
            "risk_multiplier": numeric(raw[risk_multiplier_col]),
            "capital_exposure": numeric(raw[capital_exposure_col]),
            "signed_notional_exposure": numeric(raw[signed_notional_col]),
            "gross_notional_exposure": numeric(raw[gross_notional_col]),
            "risk_exposure": numeric(raw[risk_exposure_col]),
            "capital_weight": numeric(raw[capital_weight_col]),
            "gross_exposure_weight": numeric(raw[gross_weight_col]),
            "signed_notional_weight": numeric(
                raw[signed_notional_weight_col]
            ),
            "risk_weight": numeric(raw[risk_weight_col]),
            "notional_weight": numeric(raw[notional_weight_col]),
        }
    )

    if df["symbol"].duplicated().any():
        duplicates = df.loc[
            df["symbol"].duplicated(keep=False),
            "symbol",
        ].tolist()

        raise ValueError(
            "Duplicate instrument identifiers found: "
            f"{duplicates}"
        )

    return df


# ======================================================================
# PORTFOLIO CAPITAL BASE
# ======================================================================

def estimate_capital_base(df: pd.DataFrame) -> float:
    """
    Recover the portfolio capital base from Day 64 capital exposure/weights.

    Multiple observations are used and the median is taken for robustness.
    """

    valid = (
        np.isfinite(df["capital_exposure"])
        & np.isfinite(df["capital_weight"])
        & (df["capital_weight"].abs() > POLICY.epsilon)
    )

    estimates = (
        df.loc[valid, "capital_exposure"]
        / df.loc[valid, "capital_weight"]
    ).abs()

    estimates = estimates[
        np.isfinite(estimates)
        & (estimates > POLICY.epsilon)
    ]

    if estimates.empty:
        raise ValueError(
            "Unable to infer portfolio capital base from Day 64."
        )

    capital_base = float(estimates.median())

    if not finite(capital_base) or capital_base <= 0:
        raise ValueError("Invalid inferred capital base.")

    return capital_base


# ======================================================================
# TARGET CONSTRUCTION
# ======================================================================

def determine_applicable_capital_limit(
    row: pd.Series,
) -> float:
    """
    Apply the capital concentration limit only to economically funded capital.

    Derivatives can have low capital_factor but high notional exposure, so their
    notional and risk constraints are handled independently.
    """

    capital_factor = abs(float(row["capital_factor"]))

    if capital_factor >= 0.75:
        return POLICY.max_capital_weight

    return np.inf


def build_initial_targets(df: pd.DataFrame) -> pd.DataFrame:
    """
    Begin from Day 64 exposures.

    This layer is deliberately conservative: it does not invent alpha signals.
    It keeps existing exposure unless a risk/concentration constraint requires
    scaling.
    """

    result = df.copy()

    result["target_capital_weight"] = result["capital_weight"].copy()

    result["target_gross_exposure_weight"] = (
        result["gross_exposure_weight"].copy()
    )

    result["target_signed_notional_weight"] = (
        result["signed_notional_weight"].copy()
    )

    result["target_risk_weight"] = result["risk_weight"].copy()

    result["scale_factor"] = 1.0
    result["constraint_reason"] = "UNCHANGED"

    return result


def instrument_scale_factor(row: pd.Series) -> tuple[float, list[str]]:
    scale = 1.0
    reasons: list[str] = []

    capital_limit = determine_applicable_capital_limit(row)

    capital_weight = abs(float(row["capital_weight"]))
    gross_weight = abs(float(row["gross_exposure_weight"]))
    risk_weight = abs(float(row["risk_weight"]))

    if (
        np.isfinite(capital_limit)
        and capital_weight > capital_limit + POLICY.epsilon
    ):
        scale = min(
            scale,
            capital_limit / capital_weight,
        )
        reasons.append("CAPITAL_CONCENTRATION")

    if (
        gross_weight
        > POLICY.max_single_instrument_gross_exposure
        + POLICY.epsilon
    ):
        scale = min(
            scale,
            POLICY.max_single_instrument_gross_exposure
            / gross_weight,
        )
        reasons.append("GROSS_EXPOSURE_CONCENTRATION")

    if (
        risk_weight
        > POLICY.max_single_instrument_risk_weight
        + POLICY.epsilon
    ):
        scale = min(
            scale,
            POLICY.max_single_instrument_risk_weight
            / risk_weight,
        )
        reasons.append("RISK_CONCENTRATION")

    scale = float(np.clip(scale, 0.0, 1.0))

    return scale, reasons


def apply_instrument_constraints(
    targets: pd.DataFrame,
) -> pd.DataFrame:
    result = targets.copy()

    for idx, row in result.iterrows():
        scale, reasons = instrument_scale_factor(row)

        result.at[idx, "scale_factor"] = scale

        if reasons:
            result.at[idx, "constraint_reason"] = "|".join(reasons)

        result.at[idx, "target_capital_weight"] = (
            row["capital_weight"] * scale
        )

        result.at[idx, "target_gross_exposure_weight"] = (
            row["gross_exposure_weight"] * scale
        )

        result.at[idx, "target_signed_notional_weight"] = (
            row["signed_notional_weight"] * scale
        )

        result.at[idx, "target_risk_weight"] = (
            row["risk_weight"] * scale
        )

    return result


def apply_portfolio_gross_limit(
    targets: pd.DataFrame,
) -> pd.DataFrame:
    result = targets.copy()

    gross_total = float(
        result["target_gross_exposure_weight"].abs().sum()
    )

    if (
        gross_total
        <= POLICY.max_portfolio_gross_exposure
        + POLICY.epsilon
    ):
        return result

    portfolio_scale = (
        POLICY.max_portfolio_gross_exposure / gross_total
    )

    exposure_columns = [
        "target_capital_weight",
        "target_gross_exposure_weight",
        "target_signed_notional_weight",
        "target_risk_weight",
    ]

    result[exposure_columns] = (
        result[exposure_columns] * portfolio_scale
    )

    result["scale_factor"] = (
        result["scale_factor"] * portfolio_scale
    )

    result["constraint_reason"] = np.where(
        result["constraint_reason"].eq("UNCHANGED"),
        "PORTFOLIO_GROSS_LIMIT",
        result["constraint_reason"]
        + "|PORTFOLIO_GROSS_LIMIT",
    )

    return result


def apply_portfolio_notional_limit(
    targets: pd.DataFrame,
) -> pd.DataFrame:
    result = targets.copy()

    absolute_notional = float(
        result["target_signed_notional_weight"].abs().sum()
    )

    if (
        absolute_notional
        <= POLICY.max_portfolio_absolute_notional
        + POLICY.epsilon
    ):
        return result

    portfolio_scale = (
        POLICY.max_portfolio_absolute_notional
        / absolute_notional
    )

    exposure_columns = [
        "target_capital_weight",
        "target_gross_exposure_weight",
        "target_signed_notional_weight",
        "target_risk_weight",
    ]

    result[exposure_columns] = (
        result[exposure_columns] * portfolio_scale
    )

    result["scale_factor"] = (
        result["scale_factor"] * portfolio_scale
    )

    result["constraint_reason"] = np.where(
        result["constraint_reason"].eq("UNCHANGED"),
        "PORTFOLIO_NOTIONAL_LIMIT",
        result["constraint_reason"]
        + "|PORTFOLIO_NOTIONAL_LIMIT",
    )

    return result


# ======================================================================
# ORDERS
# ======================================================================

def build_orders(
    targets: pd.DataFrame,
    capital_base: float,
) -> pd.DataFrame:
    result = targets.copy()

    result["current_capital_dollars"] = (
        result["capital_weight"] * capital_base
    )

    result["target_capital_dollars"] = (
        result["target_capital_weight"] * capital_base
    )

    result["capital_trade_dollars"] = (
        result["target_capital_dollars"]
        - result["current_capital_dollars"]
    )

    result["capital_trade_weight"] = (
        result["target_capital_weight"]
        - result["capital_weight"]
    )

    result["gross_exposure_change"] = (
        result["target_gross_exposure_weight"]
        - result["gross_exposure_weight"]
    )

    result["signed_notional_change"] = (
        result["target_signed_notional_weight"]
        - result["signed_notional_weight"]
    )

    result["risk_weight_change"] = (
        result["target_risk_weight"]
        - result["risk_weight"]
    )

    def classify_action(row: pd.Series) -> str:
        changes = [
            abs(float(row["capital_trade_weight"])),
            abs(float(row["gross_exposure_change"])),
            abs(float(row["signed_notional_change"])),
            abs(float(row["risk_weight_change"])),
        ]

        if max(changes) <= POLICY.trade_tolerance:
            return "HOLD"

        # Direction is based primarily on economic/notional exposure.
        if row["signed_notional_change"] > POLICY.trade_tolerance:
            return "BUY"

        if row["signed_notional_change"] < -POLICY.trade_tolerance:
            return "SELL"

        if row["capital_trade_weight"] > POLICY.trade_tolerance:
            return "BUY"

        if row["capital_trade_weight"] < -POLICY.trade_tolerance:
            return "SELL"

        return "HOLD"

    result["action"] = result.apply(
        classify_action,
        axis=1,
    )

    return result


# ======================================================================
# TURNOVER CONTROL
# ======================================================================

def calculate_one_way_turnover(
    orders: pd.DataFrame,
) -> float:
    """
    One-way turnover is half of total absolute capital-weight change.
    """

    return float(
        0.5
        * orders["capital_trade_weight"].abs().sum()
    )


def apply_turnover_limit(
    original: pd.DataFrame,
    targets: pd.DataFrame,
) -> pd.DataFrame:
    result = targets.copy()

    capital_changes = (
        result["target_capital_weight"]
        - original["capital_weight"]
    )

    turnover = float(
        0.5 * capital_changes.abs().sum()
    )

    if turnover <= POLICY.max_one_way_turnover + POLICY.epsilon:
        return result

    scale = POLICY.max_one_way_turnover / turnover

    mappings = [
        ("capital_weight", "target_capital_weight"),
        (
            "gross_exposure_weight",
            "target_gross_exposure_weight",
        ),
        (
            "signed_notional_weight",
            "target_signed_notional_weight",
        ),
        ("risk_weight", "target_risk_weight"),
    ]

    for current_col, target_col in mappings:
        result[target_col] = (
            original[current_col]
            + scale
            * (
                result[target_col]
                - original[current_col]
            )
        )

    result["constraint_reason"] = np.where(
        result["constraint_reason"].eq("UNCHANGED"),
        "TURNOVER_LIMIT",
        result["constraint_reason"] + "|TURNOVER_LIMIT",
    )

    return result


# ======================================================================
# COVARIANCE RISK CONTRIBUTIONS
# ======================================================================

_RISK_INPUTS: dict = {}


def risk_inputs():
    """Enriched instruments and risk history, loaded once."""
    if not _RISK_INPUTS:
        instruments = load_enriched_instruments()
        history, source = load_risk_history(instruments)
        _RISK_INPUTS.update(
            instruments=instruments,
            history=history,
            source=source,
        )
    return _RISK_INPUTS


def recalculate_target_risk(
    targets: pd.DataFrame,
) -> pd.DataFrame:
    """
    Euler risk contribution of each position in the target portfolio.

    Risk contributions are not linear in position size (shrinking one
    position changes everyone's share), so they are recomputed from the
    target exposures instead of being scaled with the position.
    """
    inputs = risk_inputs()
    shares, _, _ = portfolio_risk_shares(
        dict(
            zip(
                targets["symbol"],
                targets["target_signed_notional_weight"],
            )
        ),
        inputs["instruments"],
        history=inputs["history"],
    )
    result = targets.copy()
    result["target_risk_weight"] = (
        shares.reindex(result["symbol"]).fillna(0.0).to_numpy()
    )
    return result


def apply_risk_contribution_limit(
    targets: pd.DataFrame,
    max_iterations: int = 50,
) -> pd.DataFrame:
    """
    Scale down positions whose Euler risk contribution exceeds the
    single-instrument risk limit, recomputing contributions each pass
    until every position is within the limit.
    """
    cap = POLICY.max_single_instrument_risk_weight
    exposure_columns = [
        "target_capital_weight",
        "target_gross_exposure_weight",
        "target_signed_notional_weight",
    ]
    result = recalculate_target_risk(targets)
    for _ in range(max_iterations):
        excess = result["target_risk_weight"] > cap + POLICY.epsilon
        if not excess.any():
            break
        factor = (
            cap
            / result.loc[excess, "target_risk_weight"]
        ).clip(upper=1.0)
        for column in exposure_columns:
            result.loc[excess, column] = (
                result.loc[excess, column] * factor
            )
        result.loc[excess, "scale_factor"] = (
            result.loc[excess, "scale_factor"] * factor
        )
        needs_reason = excess & ~result["constraint_reason"].str.contains(
            "RISK_CONCENTRATION"
        )
        result.loc[needs_reason, "constraint_reason"] = np.where(
            result.loc[needs_reason, "constraint_reason"].eq("UNCHANGED"),
            "RISK_CONCENTRATION",
            result.loc[needs_reason, "constraint_reason"]
            + "|RISK_CONCENTRATION",
        )
        result = recalculate_target_risk(result)
    return result


# ======================================================================
# CONSTRAINT CHECKS
# ======================================================================

def build_constraint_checks(
    orders: pd.DataFrame,
) -> pd.DataFrame:
    rows: list[dict] = []

    # --------------------------------------------------------------
    # Fully funded capital concentration
    # --------------------------------------------------------------

    funded = orders[
        orders["capital_factor"].abs() >= 0.75
    ].copy()

    largest_funded_capital = (
        float(funded["target_capital_weight"].abs().max())
        if not funded.empty
        else 0.0
    )

    rows.append(
        {
            "check": "Fully funded capital concentration",
            "passed": (
                largest_funded_capital
                <= POLICY.max_capital_weight
                + POLICY.epsilon
            ),
            "value": largest_funded_capital,
            "limit": POLICY.max_capital_weight,
            "details": (
                f"Largest applicable target capital weight: "
                f"{largest_funded_capital:.4%}; "
                f"limit: {POLICY.max_capital_weight:.4%}"
            ),
        }
    )

    # --------------------------------------------------------------
    # Single instrument gross exposure
    # --------------------------------------------------------------

    max_gross = float(
        orders["target_gross_exposure_weight"]
        .abs()
        .max()
    )

    rows.append(
        {
            "check": "Single instrument gross exposure",
            "passed": (
                max_gross
                <= POLICY.max_single_instrument_gross_exposure
                + POLICY.epsilon
            ),
            "value": max_gross,
            "limit": POLICY.max_single_instrument_gross_exposure,
            "details": (
                f"Largest instrument gross exposure weight: "
                f"{max_gross:.4%}"
            ),
        }
    )

    # --------------------------------------------------------------
    # Single instrument risk concentration
    # --------------------------------------------------------------

    max_risk = float(
        orders["target_risk_weight"].abs().max()
    )

    rows.append(
        {
            "check": "Single instrument risk concentration",
            "passed": (
                max_risk
                <= POLICY.max_single_instrument_risk_weight
                + POLICY.epsilon
            ),
            "value": max_risk,
            "limit": POLICY.max_single_instrument_risk_weight,
            "details": (
                f"Largest instrument target risk weight: "
                f"{max_risk:.4%}"
            ),
        }
    )

    # --------------------------------------------------------------
    # Portfolio gross exposure
    # --------------------------------------------------------------

    portfolio_gross = float(
        orders["target_gross_exposure_weight"]
        .abs()
        .sum()
    )

    rows.append(
        {
            "check": "Portfolio gross exposure",
            "passed": (
                portfolio_gross
                <= POLICY.max_portfolio_gross_exposure
                + POLICY.epsilon
            ),
            "value": portfolio_gross,
            "limit": POLICY.max_portfolio_gross_exposure,
            "details": (
                f"Target portfolio gross exposure: "
                f"{portfolio_gross:.4f}x capital"
            ),
        }
    )

    # --------------------------------------------------------------
    # Absolute signed notional
    # --------------------------------------------------------------

    absolute_notional = float(
        orders["target_signed_notional_weight"]
        .abs()
        .sum()
    )

    rows.append(
        {
            "check": "Portfolio absolute notional exposure",
            "passed": (
                absolute_notional
                <= POLICY.max_portfolio_absolute_notional
                + POLICY.epsilon
            ),
            "value": absolute_notional,
            "limit": POLICY.max_portfolio_absolute_notional,
            "details": (
                f"Absolute target signed notional: "
                f"{absolute_notional:.4f}x capital"
            ),
        }
    )

    # --------------------------------------------------------------
    # Turnover
    # --------------------------------------------------------------

    turnover = calculate_one_way_turnover(orders)

    rows.append(
        {
            "check": "One-way turnover",
            "passed": (
                turnover
                <= POLICY.max_one_way_turnover
                + POLICY.epsilon
            ),
            "value": turnover,
            "limit": POLICY.max_one_way_turnover,
            "details": (
                f"One-way turnover: {turnover:.4%}; "
                f"limit: {POLICY.max_one_way_turnover:.4%}"
            ),
        }
    )

    # --------------------------------------------------------------
    # Valid actions
    # --------------------------------------------------------------

    allowed_actions = {"BUY", "SELL", "HOLD"}

    actions_valid = bool(
        orders["action"].isin(allowed_actions).all()
    )

    rows.append(
        {
            "check": "Valid rebalance actions",
            "passed": actions_valid,
            "value": float(actions_valid),
            "limit": 1.0,
            "details": "Allowed actions: BUY, SELL, HOLD",
        }
    )

    # --------------------------------------------------------------
    # Finite output
    # --------------------------------------------------------------

    numeric_columns = [
        "target_capital_weight",
        "target_gross_exposure_weight",
        "target_signed_notional_weight",
        "target_risk_weight",
        "capital_trade_weight",
        "risk_weight_change",
    ]

    finite_outputs = bool(
        np.isfinite(
            orders[numeric_columns].to_numpy(dtype=float)
        ).all()
    )

    rows.append(
        {
            "check": "Finite exposure-aware outputs",
            "passed": finite_outputs,
            "value": float(finite_outputs),
            "limit": 1.0,
            "details": (
                "Target exposure and rebalance fields "
                "must contain finite values."
            ),
        }
    )

    return pd.DataFrame(rows)


# ======================================================================
# SUMMARY
# ======================================================================

def build_portfolio_summary(
    original: pd.DataFrame,
    orders: pd.DataFrame,
    capital_base: float,
) -> pd.DataFrame:
    current_gross = float(
        original["gross_exposure_weight"].abs().sum()
    )

    target_gross = float(
        orders["target_gross_exposure_weight"]
        .abs()
        .sum()
    )

    current_net_notional = float(
        original["signed_notional_weight"].sum()
    )

    target_net_notional = float(
        orders["target_signed_notional_weight"].sum()
    )

    current_absolute_notional = float(
        original["signed_notional_weight"].abs().sum()
    )

    target_absolute_notional = float(
        orders["target_signed_notional_weight"]
        .abs()
        .sum()
    )

    current_risk_total = float(
        original["risk_weight"].abs().sum()
    )

    target_risk_total = float(
        orders["target_risk_weight"].abs().sum()
    )

    current_max_capital = float(
        original["capital_weight"].abs().max()
    )

    target_max_capital = float(
        orders["target_capital_weight"].abs().max()
    )

    current_max_risk = float(
        original["risk_weight"].abs().max()
    )

    target_max_risk = float(
        orders["target_risk_weight"].abs().max()
    )

    turnover = calculate_one_way_turnover(orders)

    buy_count = int((orders["action"] == "BUY").sum())
    sell_count = int((orders["action"] == "SELL").sum())
    hold_count = int((orders["action"] == "HOLD").sum())

    summary = pd.DataFrame(
        [
            {
                "capital_base": capital_base,
                "instrument_count": len(orders),
                "current_gross_exposure": current_gross,
                "target_gross_exposure": target_gross,
                "current_net_notional": current_net_notional,
                "target_net_notional": target_net_notional,
                "current_absolute_notional": (
                    current_absolute_notional
                ),
                "target_absolute_notional": (
                    target_absolute_notional
                ),
                "current_total_risk_weight": current_risk_total,
                "target_total_risk_weight": target_risk_total,
                "current_max_capital_weight": current_max_capital,
                "target_max_capital_weight": target_max_capital,
                "current_max_risk_weight": current_max_risk,
                "target_max_risk_weight": target_max_risk,
                "one_way_turnover": turnover,
                "buy_count": buy_count,
                "sell_count": sell_count,
                "hold_count": hold_count,
            }
        ]
    )

    return summary


# ======================================================================
# VALIDATION
# ======================================================================

def build_validation_summary(
    original: pd.DataFrame,
    orders: pd.DataFrame,
    checks: pd.DataFrame,
    summary: pd.DataFrame,
) -> pd.DataFrame:
    rows: list[dict] = []

    def add(
        check: str,
        passed: bool,
        details: str,
    ) -> None:
        rows.append(
            {
                "check": check,
                "passed": bool(passed),
                "details": details,
            }
        )

    add(
        "Day 64 input loaded",
        len(original) > 0,
        f"Rows: {len(original)}",
    )

    add(
        "Exposure-aware targets generated",
        len(orders) == len(original),
        (
            f"Input instruments: {len(original)}; "
            f"output instruments: {len(orders)}"
        ),
    )

    add(
        "Unique instrument identifiers",
        not orders["symbol"].duplicated().any(),
        f"Unique symbols: {orders['symbol'].nunique()}",
    )

    add(
        "All actions valid",
        orders["action"].isin(
            {"BUY", "SELL", "HOLD"}
        ).all(),
        "Allowed actions: BUY, SELL, HOLD",
    )

    add(
        "Constraint diagnostics generated",
        not checks.empty,
        f"Checks: {len(checks)}",
    )

    add(
        "All exposure constraints passed",
        bool(checks["passed"].all()),
        (
            f"Passed: {int(checks['passed'].sum())}/"
            f"{len(checks)}"
        ),
    )

    add(
        "Portfolio summary generated",
        len(summary) == 1,
        f"Rows: {len(summary)}",
    )

    exposure_cols = [
        "target_capital_weight",
        "target_gross_exposure_weight",
        "target_signed_notional_weight",
        "target_risk_weight",
    ]

    add(
        "Target exposures contain finite values",
        np.isfinite(
            orders[exposure_cols].to_numpy(dtype=float)
        ).all(),
        "Capital, gross, notional and risk targets checked.",
    )

    add(
        "Turnover within policy",
        calculate_one_way_turnover(orders)
        <= POLICY.max_one_way_turnover + POLICY.epsilon,
        (
            f"Turnover: "
            f"{calculate_one_way_turnover(orders):.4%}; "
            f"limit: {POLICY.max_one_way_turnover:.4%}"
        ),
    )

    # Critical derivative-aware validation:
    derivative_mask = (
        orders["capital_factor"].abs()
        < orders["notional_factor"].abs()
    )

    derivative_separation_exists = True

    if derivative_mask.any():
        derivative_separation_exists = bool(
            (
                orders.loc[
                    derivative_mask,
                    "gross_notional_exposure",
                ].abs()
                >=
                orders.loc[
                    derivative_mask,
                    "capital_exposure",
                ].abs()
            ).all()
        )

    add(
        "Derivative capital and notional remain separated",
        derivative_separation_exists,
        (
            "Derivative-like positions retain distinct "
            "capital and notional treatment."
        ),
    )

    validation = pd.DataFrame(rows)

    validation["passed_tests"] = int(
        validation["passed"].sum()
    )

    validation["total_tests"] = len(validation)

    validation["pass_rate"] = (
        validation["passed_tests"]
        / validation["total_tests"]
    )

    return validation


# ======================================================================
# OUTPUT
# ======================================================================

def save_outputs(
    orders: pd.DataFrame,
    summary: pd.DataFrame,
    checks: pd.DataFrame,
    validation: pd.DataFrame,
) -> None:
    target_columns = [
        "symbol",
        "asset_class",
        "instrument_type",
        "capital_weight",
        "target_capital_weight",
        "gross_exposure_weight",
        "target_gross_exposure_weight",
        "signed_notional_weight",
        "target_signed_notional_weight",
        "risk_weight",
        "target_risk_weight",
        "scale_factor",
        "constraint_reason",
    ]

    order_columns = [
        "symbol",
        "asset_class",
        "instrument_type",
        "action",
        "capital_weight",
        "target_capital_weight",
        "capital_trade_weight",
        "capital_trade_dollars",
        "gross_exposure_weight",
        "target_gross_exposure_weight",
        "gross_exposure_change",
        "signed_notional_weight",
        "target_signed_notional_weight",
        "signed_notional_change",
        "risk_weight",
        "target_risk_weight",
        "risk_weight_change",
        "constraint_reason",
    ]

    orders[target_columns].to_csv(
        OUTPUT_TARGETS,
        index=False,
    )

    orders[order_columns].to_csv(
        OUTPUT_ORDERS,
        index=False,
    )

    summary.to_csv(
        OUTPUT_SUMMARY,
        index=False,
    )

    checks.to_csv(
        OUTPUT_CHECKS,
        index=False,
    )

    validation.to_csv(
        OUTPUT_VALIDATION,
        index=False,
    )


# ======================================================================
# DISPLAY
# ======================================================================

def print_report(
    orders: pd.DataFrame,
    summary: pd.DataFrame,
    checks: pd.DataFrame,
    validation: pd.DataFrame,
) -> None:
    print()
    print("=" * 78)
    print("VITTANTRA - EXPOSURE-AWARE REBALANCER")
    print("=" * 78)

    print()
    print("Portfolio summary:")
    print(summary.to_string(index=False))

    print()
    print("Constraint checks:")
    print(
        checks[
            ["check", "passed", "value", "limit"]
        ].to_string(index=False)
    )

    changed = orders[
        orders["action"] != "HOLD"
    ].copy()

    print()
    print("Proposed exposure-aware actions:")

    if changed.empty:
        print(
            "No rebalance required under the current "
            "exposure policy."
        )
    else:
        display_columns = [
            "symbol",
            "asset_class",
            "instrument_type",
            "action",
            "capital_weight",
            "target_capital_weight",
            "gross_exposure_weight",
            "target_gross_exposure_weight",
            "risk_weight",
            "target_risk_weight",
            "constraint_reason",
        ]

        print(
            changed[display_columns]
            .sort_values(
                "risk_weight",
                key=lambda s: s.abs(),
                ascending=False,
            )
            .to_string(index=False)
        )

    print()
    print("Validation:")
    print(
        validation[
            ["check", "passed", "details"]
        ].to_string(index=False)
    )

    pass_rate = float(
        validation["pass_rate"].iloc[0]
    )

    print()
    print(
        f"Validation pass rate: "
        f"{pass_rate:.2%}"
    )

    print()
    print("Generated files:")
    print(f"  {OUTPUT_ORDERS}")
    print(f"  {OUTPUT_TARGETS}")
    print(f"  {OUTPUT_SUMMARY}")
    print(f"  {OUTPUT_CHECKS}")
    print(f"  {OUTPUT_VALIDATION}")

    print()
    print("Architecture:")
    print(
        "Portfolio -> Exposure Engine -> Capital / Notional / Risk -> "
        "Constraint Layer -> Exposure-Aware Rebalancing -> Validation"
    )

    print()
    print(
        "Important: rebalance proposals are conditional research outputs. "
        "They are not automatic trade instructions."
    )


# ======================================================================
# MAIN
# ======================================================================

def main() -> None:
    original = load_day64()

    capital_base = estimate_capital_base(original)

    targets = build_initial_targets(original)

    targets = apply_instrument_constraints(targets)

    targets = apply_risk_contribution_limit(targets)

    targets = apply_portfolio_gross_limit(targets)

    targets = apply_portfolio_notional_limit(targets)

    targets = apply_turnover_limit(
        original,
        targets,
    )

    targets = recalculate_target_risk(targets)

    orders = build_orders(
        targets,
        capital_base,
    )

    checks = build_constraint_checks(orders)

    summary = build_portfolio_summary(
        original,
        orders,
        capital_base,
    )

    validation = build_validation_summary(
        original,
        orders,
        checks,
        summary,
    )

    save_outputs(
        orders,
        summary,
        checks,
        validation,
    )

    print_report(
        orders,
        summary,
        checks,
        validation,
    )


if __name__ == "__main__":
    main()